<a href="https://colab.research.google.com/github/vvelvadapu9/DemoAIProj/blob/Dev/WordEmbedding1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#!pip install gensim

from gensim.models import Word2Vec
text=["the", "cat", "sits", "on", "the", "mat"], ["the", "dog", "plays", "in", "the", "garden"],["cats", "and", "dogs", "are", "friends"]
#print(text)

model = Word2Vec(text,vector_size=100, window=5, min_count=1, sg=1)
vector = model.wv['cat']
print("Vector for 'Cat':" ,vector)
print(len(vector))

(['the', 'cat', 'sits', 'on', 'the', 'mat'], ['the', 'dog', 'plays', 'in', 'the', 'garden'], ['cats', 'and', 'dogs', 'are', 'friends'])
Vector for 'Cat': [-0.00950012  0.00956222 -0.00777076 -0.00264551 -0.00490641 -0.0049667
 -0.00802359 -0.00778358 -0.00455321 -0.00127536 -0.00510299  0.00614054
 -0.00951662 -0.0053071   0.00943715  0.00699133  0.00767582  0.00423474
  0.00050709 -0.00598114  0.00601878  0.00263503  0.00769943  0.00639384
  0.00794257  0.00865741 -0.00989575 -0.0067557   0.00133757  0.0064403
  0.00737382  0.00551698  0.00766163 -0.00512557  0.00658441 -0.00410837
 -0.00905534  0.00914168  0.0013314  -0.00275968 -0.00247784 -0.00422048
  0.00481234  0.00440022 -0.00265336 -0.00734188 -0.00356585 -0.00033661
  0.00609589 -0.00283734 -0.00012089  0.00087973 -0.00709565  0.002065
 -0.00143242  0.00280215  0.00484222 -0.00135202 -0.00278014  0.00773865
  0.0050456   0.00671352  0.00451564  0.00866716  0.00747497 -0.00108189
  0.00874764  0.00460172  0.00544063 -0.00138608 -0.00204132 -0.00442435
 -0.0085152   0.00303773  0.00888319  0.00891974 -0.00194235  0.00608616
  0.00377972 -0.00429597  0.00204292 -0.00543789  0.00820889  0.00543291
  0.00318443  0.00410257  0.00865715  0.00727203 -0.00083347 -0.00707277
  0.00838047  0.00723358  0.00173047 -0.00134749 -0.00589009 -0.00453309
  0.00864797 -0.00313511 -0.00633882  0.00987008]
100

In [6]:
vector = model.wv['the']
print("Vector for 'the':" ,vector)
print(len(vector))

Vector for 'the': [-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -1.5080082e-03  2.4697948e-03 -8.8802696e-04  5.5336617e-03
 -2.7429771e-03  2.2600652e-03  5.4557943e-03  8.3459532e-03
 -1.4537406e-03 -9.2081428e-03  4.3705525e-03  5.7178497e-04
  7.4419081e-03 -8.1328274e-04 -2.6384138e-03 -8.7530091e-03
 -8.5655687e-04  2.8265631e-03  5.4014288e-03  7.0526563e-03
 -5.7031214e-03  1.8588197e-03  6.0888636e-03 -4.7980510e-03
 -3.1072604e-03  6.7976294e-03  1.6314756e-03  1.8991709e-04
  3.4736372e-03  2.1777749e-04  9.6188262e-03  5.0606038e-03
 -8.9173904e-03 -7.0415605e-03  9.0145587e-04  6.3925339e-03]
100

In [8]:
#Find the most similar words to 'cat'
similar_words = model.wv.most_similar('cat', topn=5)
print("Most similar words to 'cat':", similar_words)
print(len(similar_words))

Most similar words to 'cat': [('and', 0.25290459394454956), ('friends', 0.13725271821022034), ('cats', 0.04410674050450325), ('garden', 0.01281161978840828), ('dogs', 0.006598459556698799)]
5

In [9]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [10]:
text = "the quick brown fox jumps over the lazy dog"
print(text)

the quick brown fox jumps over the lazy dog

In [11]:
from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
print(tokens)

['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

In [12]:
# Parts of Speech (POS) tagging

nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [14]:
from nltk import pos_tag
pos_tags = pos_tag(tokens)
pos_tags

[('the', 'DT'),
 ('quick', 'JJ'),
 ('brown', 'NN'),
 ('fox', 'NN'),
 ('jumps', 'VBZ'),
 ('over', 'IN'),
 ('the', 'DT'),
 ('lazy', 'JJ'),
 ('dog', 'NN')]

In [15]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

True

In [16]:
text = """
Barack Obama was born on August 4, 1961, in Honolulu, Hawaii.He served as the 44th President of the United States from 2009 to 2017.
Apple Inc., headquartered in Cupertino, California, is a leading technology company.
"""
print(text)

Barack Obama was born on August 4, 1961, in Honolulu, Hawaii.He served as the 44th President of the United States from 2009 to 2017.
Apple Inc., headquartered in Cupertino, California, is a leading technology company.

In [18]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [19]:
from nltk.tokenize import word_tokenize
words = word_tokenize(text)
print(words)

['Barack', 'Obama', 'was', 'born', 'on', 'August', '4', ',', '1961', ',', 'in', 'Honolulu', ',', 'Hawaii.He', 'served', 'as', 'the', '44th', 'President', 'of', 'the', 'United', 'States', 'from', '2009', 'to', '2017', '.', 'Apple', 'Inc.', ',', 'headquartered', 'in', 'Cupertino', ',', 'California', ',', 'is', 'a', 'leading', 'technology', 'company', '.']

In [20]:
# Parts of Speech (POS) tagging
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [21]:
from nltk import pos_tag
pos_tags = pos_tag(words)
print(pos_tags)

[('Barack', 'NNP'), ('Obama', 'NNP'), ('was', 'VBD'), ('born', 'VBN'), ('on', 'IN'), ('August', 'NNP'), ('4', 'CD'), (',', ','), ('1961', 'CD'), (',', ','), ('in', 'IN'), ('Honolulu', 'NNP'), (',', ','), ('Hawaii.He', 'NNP'), ('served', 'VBD'), ('as', 'IN'), ('the', 'DT'), ('44th', 'CD'), ('President', 'NNP'), ('of', 'IN'), ('the', 'DT'), ('United', 'NNP'), ('States', 'NNPS'), ('from', 'IN'), ('2009', 'CD'), ('to', 'TO'), ('2017', 'CD'), ('.', '.'), ('Apple', 'NNP'), ('Inc.', 'NNP'), (',', ','), ('headquartered', 'VBD'), ('in', 'IN'), ('Cupertino', 'NNP'), (',', ','), ('California', 'NNP'), (',', ','), ('is', 'VBZ'), ('a', 'DT'), ('leading', 'VBG'), ('technology', 'NN'), ('company', 'NN'), ('.', '.')]

In [23]:
nltk.download('maxent_ne_chunker_tab')
from nltk import ne_chunk

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.

In [26]:
ner=ne_chunk(pos_tags)
print(ner)

(S
  (PERSON Barack/NNP)
  (PERSON Obama/NNP)
  was/VBD
  born/VBN
  on/IN
  August/NNP
  4/CD
  ,/,
  1961/CD
  ,/,
  in/IN
  (GPE Honolulu/NNP)
  ,/,
  Hawaii.He/NNP
  served/VBD
  as/IN
  the/DT
  44th/CD
  President/NNP
  of/IN
  the/DT
  (GPE United/NNP States/NNPS)
  from/IN
  2009/CD
  to/TO
  2017/CD
  ./.
  (PERSON Apple/NNP Inc./NNP)
  ,/,
  headquartered/VBD
  in/IN
  (GPE Cupertino/NNP)
  ,/,
  (GPE California/NNP)
  ,/,
  is/VBZ
  a/DT
  leading/VBG
  technology/NN
  company/NN
  ./.)

Machine is learning - complex pattern

In simple terms, Models are nothing but patterns identified from large volume of data. In other words, results of a machine learning using an algorithm and leveraging data is called model (Machine learning model).

Model is outcome; ML model to provide the outcome requires algorithm and data.

Deep neural networks -> Neural network with multiple stages

ANN - Artificial Neural network;
Algorithm is a program that assists model to detect patterns within trained data set.

ML models -> Scikit algorightm
DL models -> Tensor flow

If you use mathematial & statistical techniques in algorithm to establish relationship or pattern within a data set and not use ANN then its machine learning model.

If you use artificial neural network based algorithm it is deep learning model.

Deep learning models primarily involve NLP and/or Computer vision -

Linear Models, Tree based Algorithms, K nearest neighbor (KNN) Distance based algorithm, Probabilistic Algorithms, Margin-Based algorithm, Clustering, Dimensional Reduction, Rule based & Instance based learning .

Air Quality Index Prediction

In [1]:
# Import required libraries and load the data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
df = pd.read_csv('AQI.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [3]:
# Lets verify the percentage of missing values
df.isnull().sum()/len(df)*100

City           0.000000
Date           0.000000
PM2.5         15.570079
PM10          37.723071
NO            12.129626
NO2           12.139785
NOx           14.171549
NH3           34.973418
CO             6.972334
SO2           13.050692
O3            13.619586
Benzene       19.041008
Toluene       27.229014
Xylene        61.322001
AQI           15.851139
AQI_Bucket    15.851139
dtype: float64

In [5]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

Observations:
PM10, NH3 Toloune Xylene Columns are having more missing values - Lets drop these columns /n

Columns data is an unimportant column, lets drop date column
AQI_bucket is another form of output and can be dropped

In [6]:
df['AQI_Bucket'].value_counts()

AQI_Bucket
Moderate        8829
Satisfactory    8224
Poor            2781
Very Poor       2337
Good            1341
Severe          1338
Name: count, dtype: int64

In [11]:
# drop columns PM10, NH3, Toloune, Xylene
#df= df.drop(columns=["PM10","NH3","Toluene","Xylene"])
#df= df.drop(columns=["Date"])
#df= df.drop(columns=["AQI_Bucket"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   City     29531 non-null  object
 1   PM2.5    24933 non-null  float64
 2   NO       25949 non-null  float64
 3   NO2      25946 non-null  float64
 4   NOx      25346 non-null  float64
 5   CO       27472 non-null  float64
 6   SO2      25677 non-null  float64
 7   O3       25509 non-null  float64
 8   Benzene  23908 non-null  float64
 9   AQI      24850 non-null  float64
dtypes: float64(9), object(1)
memory usage: 2.3+ MB

In [14]:
# Update null values of columns with relevant data
# use Median
df["PM2.5"].fillna(df["PM2.5"].median())
df["NO"].fillna(df["NO"].median())
df["NO2"].fillna(df["NO2"].median())
df["NOx"].fillna(df["NOx"].median())
df["CO"].fillna(df["CO"].median())
df["SO2"].fillna(df["SO2"].median())
df["O3"].fillna(df["O3"].median())
df["Benzene"].fillna(df["Benzene"].median())
df["AQI"].fillna(df["AQI"].median())

0        118.0
1        118.0
2        118.0
3        118.0
4        118.0
         ...
29526     41.0
29527     70.0
29528     68.0
29529     54.0
29530     50.0
Name: AQI, Length: 29531, dtype: float64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   City     29531 non-null  object
 1   PM2.5    24933 non-null  float64
 2   NO       25949 non-null  float64
 3   NO2      25946 non-null  float64
 4   NOx      25346 non-null  float64
 5   CO       27472 non-null  float64
 6   SO2      25677 non-null  float64
 7   O3       25509 non-null  float64
 8   Benzene  23908 non-null  float64
 9   AQI      24850 non-null  float64
dtypes: float64(9), object(1)
memory usage: 2.3+ MB